In [1]:
import numpy as np

ベクトルと行列の表現ができる

In [3]:
x = np.array([1, 2, 3])
x

array([1, 2, 3])

In [ ]:
形を見る

In [5]:
x.shape

(3,)

xの次元数：ディメンジョン

In [7]:
x.ndim

1

In [14]:
y = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [16]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
y.shape

(3, 3)

In [22]:
y.ndim

2

zerosで全ての要素が0の行列を作ることができる

In [24]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
y

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

平均値を取ることができる

In [31]:
y.mean()

5.0

1行ごとの平均を取る方法
mean(axis=1)とすると、横の平均を取る
例　yの行列の場合
　1,2,3→平均2
　4,5,6→平均5
　7,8,9→平均8

In [35]:
y.mean(axis=1)

array([2., 5., 8.])

varで分散を表すことができる

In [40]:
y.var()

6.666666666666667

stdで標準偏差を表す

In [42]:
y.std()

2.581988897471611

max(axis=1)で行の最大値を表すことができる

In [46]:
y.max(axis=1)

array([3, 6, 9])

In [59]:
X = np.array([
    [2,3],
    [1,5],
    [3,1]
])
X

array([[2, 3],
       [1, 5],
       [3, 1]])

Tで転置することができる
※転置：行と列を入れ替えること

In [61]:
X.T

array([[2, 1, 3],
       [3, 5, 1]])

dotで行列の席を計算することができる

In [66]:
np.dot(X,X.T)

array([[13, 17,  9],
       [17, 26,  8],
       [ 9,  8, 10]])